<?php

namespace AppBundle\Repository;

/**
 * AdressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return array string
     */
    public function citiesToString()
    {
        $rc =  $this->createQueryBuilder('c')
            ->select('c.villeSlug')
            ->getQuery()->getResult();

        return $rc;
    }

    /**
     * @return array string
     */
    public function citiesDataToString($villeSlug)
    {
        $rc =  $this->createQueryBuilder('c')
            ->select('c.villeSlug, c.villeNomReel, c.villeDepartement, c.villeCodeCommune')
            ->where('c.villeSlug = :villeSlug')
            ->setParameter('villeSlug',$villeSlug)
            ->getQuery()->getResult();

        return $rc;
    }


    /**
     * @return array string
     */
    public function citiesByDep($dep)
    {
        $rc =  $this->createQueryBuilder('c')
            ->select('c.villeSlug, c.villeNomReel, c.villeCodeCommune')
            ->where('c.villeDepartement = :dep')
            ->setParameter('dep',$dep)
            ->getQuery()->getResult();

        return $rc;
    }



    /**
     * @return array string
     */
    public function getCode($villeSlug)
    {
        $rc =  $this->createQueryBuilder('c')
            ->select('c.villeCodeCommune')
            ->where('c.villeSlug = :villeSlug')
            ->setParameter('villeSlug',$villeSlug)
            ->getQuery()->getResult();

        return $rc;
    }

}
