<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Championship;


/**
 * ChampionshipCompetitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampionshipCompetitorRepository extends \Doctrine\ORM\EntityRepository

{
    /**
     * @return array string
     */
    public function competitorsOrderByPointsToString(Championship $championship)
    {
        $cc = $this->createQueryBuilder('cc')
            ->innerJoin('cc.competitor','c')
            ->select('c.code, cc.ranck, cc.points, c.firstName, c.lastName')
            ->where('cc.championship = :championship')
            ->setParameter('championship',$championship->getId())
            ->orderBy('cc.points','DESC')
            ->getQuery()->getResult();

        return $cc;
    }

    /**
     * @return array object
     */
    public function ccOrderByPoints(Championship $championship)
    {
        $cc = $this->createQueryBuilder('cc')
            ->where('cc.championship = :championship')
            ->setParameter('championship',$championship->getId())
            ->orderBy('cc.points','DESC')
            ->getQuery()->getResult();

        return $cc;
    }

    /**
     * @return array string
     */
    public function ccOrderByRanckToString($category)
    {
        $rc =  $this->createQueryBuilder('cc')
            ->innerJoin('cc.competitor', 'c')
            ->innerJoin('rc.championship', 'ch')
            ->select('c.code, c.firstName, c.lastName, cc.ranck, cc.points')
            ->where('ch.category = :category')
            ->setParameter('category', $category)
            ->orderBy('cc.ranck')
            ->getQuery()->getResult();

        return $rc;
    }
}
