<?php

namespace AppBundle\Repository;



/**
 * RaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceRepository extends \Doctrine\ORM\EntityRepository
{

    public function lastId($class)
    {
        return $this->createQueryBuilder('a')
            ->select('MAX(e.id)')
            ->from('AppBundle:'.$class, 'e')
            ->getQuery()
            ->getSingleScalarResult();
    }


}
